In [8]:
import pandas as pd
#Import DataSets

# Read the csv file
df = pd.read_csv('data_train.csv')
y_test = pd.read_csv('test_competition.csv')


Y_train = df["default.payment.next.month"]

X_train = df.drop(columns = ["default.payment.next.month"])

In [ ]:
# import joblib 

# #Splitting DataFrame
# X_train = df.iloc[:20000,:]

# Y_train = X_train["default.payment.next.month"]

# X_train = X_train.drop(columns = ["default.payment.next.month"])



# y_test = df.iloc[20000:,:]

# y_test.to_csv("test_5000.csv", index=False)

# y_test = y_test.drop(columns = ["default.payment.next.month"])
# print(y_test)



# # # 
# # y_test = df.iloc[20000:,:]
# # y_test = y_test.drop(columns = ["default.payment.next.month"])

In [40]:
# #Using smote to overSample minorities in the dataset for avoiding bias
# from imblearn.over_sampling import SMOTE

# print("Smoting...")

# # Step 2: Apply SMOTE to the training data
# smote = SMOTE(random_state=42)
# X_train, Y_train = smote.fit_resample(X_train, Y_train)

# print("Data over sampled !")

Smoting...
Data over sampled !

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
import numpy as np

def bestModelFindingWithRandomForest(param_grid, scoring, X_train, Y_train, X_train_reshape=False, Y_train_reshape=False):
    # Loading model
    print("Loading RandomForestClassifier...")
    model = RandomForestClassifier(n_estimators=100, max_depth=12, random_state=100, class_weight="balanced")

    if X_train_reshape:
        # Flatten the X_train data
        X_train = X_train.reshape(X_train.shape[0], -1)

    if Y_train_reshape:
        # Flatten the Y_train data
        Y_train = Y_train.reshape(Y_train.shape[0], -1)
    
    print("Loading RandomizedSearchCV model...")
    # Using RandomizedSearchCV with 5-fold cross-validation
    random_search = RandomizedSearchCV(
        model, param_distributions=param_grid, n_iter=20, cv=5, scoring=scoring, n_jobs=-1, random_state=42
    )
    
    print("Fitting RandomizedSearchCV model...")
    # Fit the model to find the best hyperparameters
    random_search.fit(X_train, Y_train)
    
    print("RandomizedSearchCV fitted ")
    
    # Best parameters and score obtained
    best_params = random_search.best_params_
    best_score = random_search.best_score_ * 100  # In percentage
    
    print(f"Best params : {best_params} with the score of : {best_score}")
    
    return random_search.best_estimator_

# Define the parameter grid for RandomizedSearchCV using ranges
param_grid = {
    'n_estimators': np.arange(100, 201, 50),         # Range for number of trees
    'max_depth': np.arange(10, 30, 5),                # Range for tree depth (10, 15, 20, 25)
    'min_samples_split': np.arange(2, 21, 5),         # Range for min_samples_split (2, 7, 12, 17)
    'min_samples_leaf': np.arange(1, 6),              # Range for min_samples_leaf (1, 2, 3, 4, 5)
    'max_features': ['sqrt', 0.5],                    # Reduced options for features per split
    'class_weight': ['balanced']                       # Focus on 'balanced' to handle imbalance
}

# Example: Best model search using RandomizedSearchCV
bestModel = bestModelFindingWithRandomForest(param_grid, "roc_auc", X_train, Y_train)

Loading RandomForestClassifier...
Loading GridSearch model...
Fitting GridSearch model...

/opt/anaconda3/lib/python3.12/site-packages/numpy/ma/core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,

GridSearch fitted
Best params : {'class_weight': 'balanced', 'max_depth': 10, 'max_features': 0.5, 'min_samples_leaf': 5, 'min_samples_split': 2, 'n_estimators': 200} with the score of : 56.48870777486249

In [59]:
# from sklearn.model_selection import cross_validate
# import numpy as np

# #Performance testing with Cross  Validate
# # Fitting the model
# print("Fitting RandomForestClassifier model")
# bestModel.fit(X_train, Y_train)

# scores = cross_validate(bestModel, X_train, Y_train , cv=5)
# print("Performance testing with Cross  Validate...")

# # Computing mean score
# avg_score = np.mean(scores['test_score']) * 100

# print(f"Cross validate Avg Score : {avg_score:.2f}%")

In [10]:
import pandas as pd 

# Prediction step
print("Predicting...")
predicted_survival = bestModel.predict_proba(y_test)  

# Extracting the first column of predicted probabilities
unsortedPredictedPaymentValue = predicted_survival[:, 1]

# Combining Passenger ID and predicted payment probabilities into a DataFrame
predicted_df = pd.DataFrame({
    'ID': y_test['ID'],      # Get the PassengerId from y_test
    'PAYED': unsortedPredictedPaymentValue  # Add the predicted payment probability (class 0)
})

# Sort predicted_df by the 'PAYED' column in descending order and extract sorted IDs
sorted_df = predicted_df.sort_values(by='PAYED', ascending=False)[['ID']]

# Display the resulting DataFrame of sorted IDs

sorted_df.head(1000).to_csv("sorted_df.csv", index=False)

Predicting...

In [55]:

# Convert predicted_survival to DataFrame
pred = pd.DataFrame(predicted_survival)

# Add the 'ID' column from y_test
pred["ID"] = y_test["ID"]

# Sort by the column with index 1 in descending order
sorted_pred = pred.sort_values(by=1, ascending=False)

sorted_pred.head(1000).to_csv("sorted_2_df.csv", index=False)

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,15996,140000.0,2,1,2,33,0,0,0,0,...,88736.0,91287.0,91057.0,91538.0,5000.0,5000.0,5000.0,5000.0,3500.0,3500.0
1,4676,90000.0,2,1,2,29,0,0,0,0,...,89059.0,88822.0,90978.0,89363.0,3481.0,5167.0,3300.0,3615.0,3217.0,3500.0
2,12207,30000.0,1,2,1,36,1,3,2,5,...,22630.0,21988.0,21057.0,25412.0,0.0,5000.0,0.0,0.0,5000.0,0.0
3,17804,150000.0,1,1,2,28,-2,-2,-2,-2,...,11021.0,6253.0,6257.0,4152.0,436.0,11086.0,6284.0,6288.0,4172.0,3207.0
4,7789,200000.0,1,1,1,49,2,2,2,2,...,2500.0,2500.0,2500.0,2500.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,11530,80000.0,1,3,1,42,1,-2,-2,-2,...,0.0,0.0,0.0,7010.0,0.0,0.0,0.0,0.0,6204.0,1000.0
4996,23043,160000.0,2,1,1,32,0,0,0,0,...,89231.0,67134.0,55773.0,46485.0,3805.0,2993.0,2293.0,1838.0,1687.0,2735.0
4997,29134,350000.0,2,1,1,59,-2,-2,-2,-2,...,0.0,0.0,0.0,42800.0,0.0,0.0,0.0,0.0,42800.0,0.0
4998,21812,20000.0,2,2,2,24,3,2,3,2,...,19502.0,20881.0,20266.0,20511.0,2000.0,1000.0,2000.0,0.0,700.0,0.0
4999,26762,50000.0,1,2,2,25,0,0,0,2,...,23590.0,24896.0,24200.0,26630.0,3000.0,3000.0,2000.0,0.0,3000.0,1500.0